package evaluacionparcial2;

import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Maluli
 */
public class Solucion extends javax.swing.JFrame {

    int op1Dimension = 0;
    int op1PosicionVector1 = 0;
    int op1PosicionVector2 = 0;
    float[] op1Vector1 = null;
    float[] op1Vector2 = null;

    //Variables usadas para la opcion 2
    int op2DimensionFilasM1 = 0;
    int op2DimensionColM1 = 0;

    int op2DimensionFilasM2 = 0;
    int op2DimensionColM2 = 0;

    float[][] op2Vector1 = null;
    float[][] op2Vector2 = null;

    /**
     * Creates new form Solucion
     */
    public Solucion() {
        initComponents();
        this.panelOperacion1.setVisible(false);
        this.panelOperacion2.setVisible(false);
        this.panelOperacion3.setVisible(false);
        this.panelOperacion4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        panelInicio = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelOperacion1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        op1DimensionVectores = new javax.swing.JTextField();
        op1ValorVector2 = new javax.swing.JTextField();
        op1ValorVector1 = new javax.swing.JTextField();
        op1GuardarVector2 = new javax.swing.JButton();
        op1GuardarVector1 = new javax.swing.JButton();
        op1SumarVectores = new javax.swing.JButton();
        panelOperacion2 = new javax.swing.JPanel();
        op2ValorColumaMatriz1 = new javax.swing.JTextField();
        op2GuardarValorMatriz2 = new javax.swing.JButton();
        op2ValorColumaMatriz2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        op2M1filas = new javax.swing.JTextField();
        op2GuardarValorMatriz1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        op2M1columnas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        op2M2filas = new javax.swing.JTextField();
        op2M2columnas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        op2SelectorFilaMatriz1 = new javax.swing.JComboBox<>();
        op2SelectorFilaMatriz2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        op2PreviewM1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        op2PreviewM2 = new javax.swing.JTextArea();
        op2MultiplicarMatrices = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        op2ResultadoMultiplicacion = new javax.swing.JTextArea();
        panelOperacion3 = new javax.swing.JPanel();
        panelOperacion4 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuOperacion1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnuOperacion2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuOperacion3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuOperacion4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 233, 245));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicio.setBackground(new java.awt.Color(102, 102, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jTextField1.setText("Evaluación Parcial del segundo parcial  // Maria ponce Ochoa");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setToolTipText("");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Desarrollar una aplicacion que permita desplegar un menu y realizar las acciones indicadas en cada opcion:\n\nOperacion 1: Suma de Dos vectores de n posiciones cada uno (cada vector se debe llenar por teclado).\n\nOperacion 2: Suma de dos matrices (mxn) el usuario definirá el tamaño de la matriz (cada matriz se debe llenar\n                        por teclado).\n\nOperacion 3: Multiplicacion de una matriz por un número (el tamaño de la matriz lo define el usuario), tanto la\n                      matriz como el numero multiplicador debe ser ingresado por teclado.\n\nOperacion 4: LLenar una matriz  de nxm, porteriormente imprimir los numeros ingresados que sean pares.\n\nSalir.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        panelOperacion1.setBackground(new java.awt.Color(102, 102, 255));
        panelOperacion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2.setText("Evaluación Parcial del segundo parcial  // Maria ponce Ochoa");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelOperacion1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la dimensión de ambos vectores:");
        jLabel2.setToolTipText("");
        panelOperacion1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, -1, -1));

        op1DimensionVectores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        op1DimensionVectores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                op1DimensionVectoresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                op1DimensionVectoresFocusLost(evt);
            }
        });
        op1DimensionVectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1DimensionVectoresActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1DimensionVectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 92, 25));

        op1ValorVector2.setForeground(new java.awt.Color(153, 153, 153));
        op1ValorVector2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        op1ValorVector2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ValorVector2ActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1ValorVector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 247, 270, 39));

        op1ValorVector1.setForeground(new java.awt.Color(153, 153, 153));
        op1ValorVector1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        op1ValorVector1.setOpaque(true);
        op1ValorVector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ValorVector1ActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1ValorVector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 181, 270, 39));

        op1GuardarVector2.setText("Guardar Vector 2");
        op1GuardarVector2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1GuardarVector2ActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1GuardarVector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, 40));

        op1GuardarVector1.setText("Guardar Vector 1");
        op1GuardarVector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1GuardarVector1ActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1GuardarVector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 130, 40));

        op1SumarVectores.setText("Sumar Vectores");
        op1SumarVectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1SumarVectoresActionPerformed(evt);
            }
        });
        panelOperacion1.add(op1SumarVectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 120, 40));

        getContentPane().add(panelOperacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 445));

        panelOperacion2.setBackground(new java.awt.Color(102, 102, 255));
        panelOperacion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelOperacion2.add(op2ValorColumaMatriz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 40));

        op2GuardarValorMatriz2.setText("Guardar");
        op2GuardarValorMatriz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2GuardarValorMatriz2ActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2GuardarValorMatriz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 80, 40));
        panelOperacion2.add(op2ValorColumaMatriz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 140, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Columnas");
        panelOperacion2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("columnas matriz 2");
        panelOperacion2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        op2M1filas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                op2M1filasFocusLost(evt);
            }
        });
        panelOperacion2.add(op2M1filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 40));

        op2GuardarValorMatriz1.setText("Guardar");
        op2GuardarValorMatriz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2GuardarValorMatriz1ActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2GuardarValorMatriz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("columnas matriz 1");
        panelOperacion2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        op2M1columnas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                op2M1columnasFocusLost(evt);
            }
        });
        op2M1columnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2M1columnasActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2M1columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 50, 40));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Filas");
        panelOperacion2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Columnas");
        panelOperacion2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        op2M2filas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                op2M2filasFocusLost(evt);
            }
        });
        panelOperacion2.add(op2M2filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 50, 40));

        op2M2columnas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                op2M2columnasFocusLost(evt);
            }
        });
        panelOperacion2.add(op2M2columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 50, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Filas");
        panelOperacion2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        panelOperacion2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Dimension Matriz 2");
        panelOperacion2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Dimension Matriz 1");
        panelOperacion2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        panelOperacion2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        op2SelectorFilaMatriz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2SelectorFilaMatriz1ActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2SelectorFilaMatriz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 40));

        op2SelectorFilaMatriz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2SelectorFilaMatriz2ActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2SelectorFilaMatriz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 40));

        op2PreviewM1.setEditable(false);
        op2PreviewM1.setColumns(10);
        op2PreviewM1.setRows(5);
        jScrollPane2.setViewportView(op2PreviewM1);

        panelOperacion2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 160, 110));

        op2PreviewM2.setEditable(false);
        op2PreviewM2.setColumns(10);
        op2PreviewM2.setRows(5);
        jScrollPane3.setViewportView(op2PreviewM2);

        panelOperacion2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 160, 110));

        op2MultiplicarMatrices.setText("X");
        op2MultiplicarMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2MultiplicarMatricesActionPerformed(evt);
            }
        });
        panelOperacion2.add(op2MultiplicarMatrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 50, 40));

        jLabel6.setText("=");
        panelOperacion2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 360, 20, -1));

        op2ResultadoMultiplicacion.setColumns(10);
        op2ResultadoMultiplicacion.setRows(5);
        jScrollPane4.setViewportView(op2ResultadoMultiplicacion);

        panelOperacion2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 140, 110));

        getContentPane().add(panelOperacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        panelOperacion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelOperacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        panelOperacion4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelOperacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        jMenuBar2.setBackground(new java.awt.Color(0, 0, 102));
        jMenuBar2.setBorder(null);
        jMenuBar2.setForeground(new java.awt.Color(255, 204, 204));
        jMenuBar2.setAlignmentY(2.0F);
        jMenuBar2.setAutoscrolls(true);
        jMenuBar2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N

        mnuInicio.setForeground(new java.awt.Color(255, 255, 255));
        mnuInicio.setText("Inicio");
        mnuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioActionPerformed(evt);
            }
        });
        jMenuBar2.add(mnuInicio);

        mnuOperacion1.setForeground(new java.awt.Color(255, 255, 255));
        mnuOperacion1.setText("Operación 1");
        mnuOperacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOperacion1ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Empezar");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        mnuOperacion1.add(jRadioButtonMenuItem1);

        jMenuBar2.add(mnuOperacion1);

        mnuOperacion2.setForeground(new java.awt.Color(255, 255, 255));
        mnuOperacion2.setText("Operación 2");
        mnuOperacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOperacion2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Empezar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuOperacion2.add(jMenuItem1);

        jMenuBar2.add(mnuOperacion2);

        mnuOperacion3.setForeground(new java.awt.Color(255, 255, 255));
        mnuOperacion3.setText("Operación 3");

        jMenuItem2.setText("Empezar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuOperacion3.add(jMenuItem2);

        jMenuBar2.add(mnuOperacion3);

        mnuOperacion4.setForeground(new java.awt.Color(255, 255, 255));
        mnuOperacion4.setText("Operación 4");

        jMenuItem3.setText("Empezar");
        mnuOperacion4.add(jMenuItem3);

        jMenuBar2.add(mnuOperacion4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        this.panelInicio.setVisible(false);
        this.panelOperacion1.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        panelOperacion2.setVisible(true);
        panelInicio.setVisible(false);
        panelOperacion1.setVisible(false);
        panelOperacion3.setVisible(false);
        panelOperacion4.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void op1DimensionVectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1DimensionVectoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1DimensionVectoresActionPerformed

    private void op1ValorVector2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ValorVector2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1ValorVector2ActionPerformed

    private void op1ValorVector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ValorVector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1ValorVector1ActionPerformed

    private void op1GuardarVector2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1GuardarVector2ActionPerformed
        String valorVector = this.op1ValorVector2.getText();
        if (this.op1PosicionVector2 < this.op1Dimension) {
            this.op1Vector2[this.op1PosicionVector2] = Float.parseFloat(valorVector);

            this.op1ValorVector2.setText("");
            this.op1PosicionVector2 += 1; //op1PosicionVector1 + op1PosicionVector1 + 1;
        } else {
            JOptionPane.showMessageDialog(null, "Vector 1 completo o no ha ingresado dimensiones", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.op1ValorVector2.setText("");
        }

    }//GEN-LAST:event_op1GuardarVector2ActionPerformed
    /*a partir de este boton vamos a ejecutar la suma de vectores de una misma dimension, Operacion 1*/
    private void op1GuardarVector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1GuardarVector1ActionPerformed
        String valorVector = this.op1ValorVector1.getText();
        if (this.op1PosicionVector1 < this.op1Dimension) {
            this.op1Vector1[this.op1PosicionVector1] = Float.parseFloat(valorVector);

            this.op1ValorVector1.setText("");
            this.op1PosicionVector1 += 1; //op1PosicionVector1 + op1PosicionVector1 + 1;
        } else {
            JOptionPane.showMessageDialog(null, "Vector 2 completo o no ha ingresado dimensiones", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.op1ValorVector1.setText("");
        }
    }//GEN-LAST:event_op1GuardarVector1ActionPerformed

    private void op1SumarVectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1SumarVectoresActionPerformed
        if (this.op1Dimension <= 0) {
            JOptionPane.showMessageDialog(null, "No ha ingresado la dimension de los vectores", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        float[] resultadoSumaVectores = new float[this.op1Dimension];
        for (int i = 0; i < op1Dimension; i++) {
            resultadoSumaVectores[i] = this.op1Vector1[i] + this.op1Vector2[i];
        }

        JOptionPane.showMessageDialog(null, "El vector resultante e igual a: " + Arrays.toString(resultadoSumaVectores), "Resultado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_op1SumarVectoresActionPerformed

    private void mnuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioActionPerformed
        // TODO add your handling code here:
        panelInicio.setVisible(true);
        panelOperacion1.setVisible(false);

    }//GEN-LAST:event_mnuInicioActionPerformed

    private void mnuOperacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOperacion1ActionPerformed
        // TODO add your handling code here:
        panelInicio.setVisible(false);
        panelOperacion1.setVisible(true);
    }//GEN-LAST:event_mnuOperacion1ActionPerformed

    private void op1DimensionVectoresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op1DimensionVectoresFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_op1DimensionVectoresFocusGained

    private void op1DimensionVectoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op1DimensionVectoresFocusLost
        // TODO add your handling code here:
        String numDimension = this.op1DimensionVectores.getText();

        System.out.println("Se van a crear las dimensiones de los vector con tamanio: " + numDimension);

        this.op1Dimension = !numDimension.isEmpty() ? Integer.parseInt(numDimension) : 0;
        if (this.op1Dimension < 0) {
            JOptionPane.showMessageDialog(null, "Dimension no valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.op1Vector1 = !numDimension.isEmpty() ? new float[Integer.parseInt(numDimension)] : null;
        this.op1Vector2 = !numDimension.isEmpty() ? new float[Integer.parseInt(numDimension)] : null;
        this.op1PosicionVector1 = 0;
        this.op1PosicionVector2 = 0;
    }//GEN-LAST:event_op1DimensionVectoresFocusLost

    private void op2GuardarValorMatriz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2GuardarValorMatriz2ActionPerformed
        // TODO add your handling code here:
        String valoresMatriz2 = op2ValorColumaMatriz2.getText(); //1, 2, 3, 4
        if (valoresMatriz2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor para la matriz 2", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] arregloValoresM2 = valoresMatriz2.split(",");// [1, 2, 3, 4]
        if (arregloValoresM2.length > this.op2DimensionColM2) {
            JOptionPane.showMessageDialog(null, "Valores superiores a la longitud de la matriz indicada\nValor Maximo " + this.op2DimensionColM2,
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int filaSelecionada = Integer.parseInt(this.op2SelectorFilaMatriz2.getSelectedItem().toString());
        for (int i = 0; i < arregloValoresM2.length; i++) { //[i] = [1, 2, 3, 4]
            this.op2Vector2[filaSelecionada][i] = Float.parseFloat(arregloValoresM2[i]); //[0][0] = [1]
        }

        this.refrescarPreviwOP2M2();
    }//GEN-LAST:event_op2GuardarValorMatriz2ActionPerformed

    private void op2GuardarValorMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2GuardarValorMatriz1ActionPerformed
        // TODO add your handling code here:
        String valoresMatriz1 = op2ValorColumaMatriz1.getText(); //1, 2, 3, 4
        if (valoresMatriz1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor para la matriz 1", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] arregloValoresM1 = valoresMatriz1.split(",");// [1, 2, 3, 4]
        if (arregloValoresM1.length > this.op2DimensionColM1) {
            JOptionPane.showMessageDialog(null, "Valores superiores a la longitud de la matriz indicada\nValor Maximo " + this.op2DimensionColM1,
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int filaSelecionada = Integer.parseInt(this.op2SelectorFilaMatriz1.getSelectedItem().toString());
        for (int i = 0; i < arregloValoresM1.length; i++) { //[i] = [1, 2, 3, 4]
            this.op2Vector1[filaSelecionada][i] = Float.parseFloat(arregloValoresM1[i]); //[0][0] = [1]
        }

        this.refrescarPreviwOP2M1();
    }//GEN-LAST:event_op2GuardarValorMatriz1ActionPerformed

    private void mnuOperacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOperacion2ActionPerformed

    }//GEN-LAST:event_mnuOperacion2ActionPerformed

    private void op2M1columnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2M1columnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op2M1columnasActionPerformed

    private void op2M1columnasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op2M1columnasFocusLost
        String columnas = this.op2M1columnas.getText();

        System.out.println("Se van a crear las columnas de la matriz 1: " + columnas);

        this.op2DimensionColM1 = !columnas.isEmpty() ? Integer.parseInt(columnas) : 0;
        if (this.op2DimensionColM1 < 0) {
            JOptionPane.showMessageDialog(null, "Columnas de la matriz 1 no valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.op2PreviewM1.setText("");
        this.op2Vector1 = !columnas.isEmpty() ? new float[this.op2DimensionFilasM1][this.op2DimensionColM1] : null;

        refrescarPreviwOP2M1();
    }//GEN-LAST:event_op2M1columnasFocusLost

    private void op2SelectorFilaMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2SelectorFilaMatriz1ActionPerformed

    }//GEN-LAST:event_op2SelectorFilaMatriz1ActionPerformed

    private void op2M1filasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op2M1filasFocusLost
        String filas = this.op2M1filas.getText();

        System.out.println("Se van a crear las filas de la matriz 1: " + filas);

        op2SelectorFilaMatriz1.removeAllItems();
        this.op2DimensionFilasM1 = !filas.isEmpty() ? Integer.parseInt(filas) : 0;
        if (this.op2DimensionFilasM1 < 0) {
            JOptionPane.showMessageDialog(null, "Filas de la matriz 1 no valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < this.op2DimensionFilasM1; i++) {
            op2SelectorFilaMatriz1.addItem(String.valueOf(i));
        }

        this.op2PreviewM1.setText("");
        this.op2Vector1 = !filas.isEmpty() ? new float[this.op2DimensionFilasM1][this.op2DimensionColM1] : null;

        refrescarPreviwOP2M1();

    }//GEN-LAST:event_op2M1filasFocusLost

    private void op2SelectorFilaMatriz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2SelectorFilaMatriz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op2SelectorFilaMatriz2ActionPerformed

    private void op2M2filasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op2M2filasFocusLost
        // TODO add your handling code here:
        String filas = this.op2M2filas.getText();

        System.out.println("Se van a crear las filas de la matriz 2: " + filas);

        op2SelectorFilaMatriz2.removeAllItems();
        this.op2DimensionFilasM2 = !filas.isEmpty() ? Integer.parseInt(filas) : 0;
        if (this.op2DimensionFilasM2 < 0) {
            JOptionPane.showMessageDialog(null, "Filas de la matriz 1 no valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < op2DimensionFilasM2; i++) {
            op2SelectorFilaMatriz2.addItem(String.valueOf(i));
        }

        this.op2PreviewM2.setText("");
        this.op2Vector2 = !filas.isEmpty() ? new float[this.op2DimensionFilasM2][this.op2DimensionColM2] : null;
        this.refrescarPreviwOP2M2();
    }//GEN-LAST:event_op2M2filasFocusLost

    private void op2M2columnasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_op2M2columnasFocusLost
        // TODO add your handling code here:
        String columnas = this.op2M2columnas.getText();

        System.out.println("Se van a crear las columnas de la matriz 2: " + columnas);

        this.op2DimensionColM2 = !columnas.isEmpty() ? Integer.parseInt(columnas) : 0;
        if (this.op2DimensionColM2 < 0) {
            JOptionPane.showMessageDialog(null, "Columnas de la matriz 1 no valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.op2PreviewM2.setText("");
        this.op2Vector2 = !columnas.isEmpty() ? new float[this.op2DimensionFilasM2][this.op2DimensionColM2] : null;
        this.refrescarPreviwOP2M2();
    }//GEN-LAST:event_op2M2columnasFocusLost

    private void op2MultiplicarMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2MultiplicarMatricesActionPerformed
        // TODO add your handling code here:
        if (this.op2DimensionFilasM2 != this.op2DimensionColM1) {
            JOptionPane.showMessageDialog(null, "Dimension de matrices incorrectas. No se puede multiplicar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        float [][] resultado = new float[this.op2DimensionFilasM1][this.op2DimensionColM2];
        
        for (int i = 0; i < op2Vector1.length; i++) {
            for (int j = 0; j < op2Vector2[0].length; j++) {
                for (int k = 0; k < op2Vector1[0].length; k++) {
                    // aquí se multiplica la matriz
                    resultado[i][j] += op2Vector1[i][k] * op2Vector2[k][j];
                }
            }
        }
        
        System.out.println(Arrays.deepToString(resultado));
        
        this.op2ResultadoMultiplicacion.setText("");
        for (int i = 0; i < this.op2DimensionFilasM1; i++) {
            this.op2ResultadoMultiplicacion.append(Arrays.toString(resultado[i]) +  "\n");
        }
    }//GEN-LAST:event_op2MultiplicarMatricesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solucion().setVisible(true);
            }
        });
    }

    //Funciones generales
    private void refrescarPreviwOP2M1() {
        this.op2PreviewM1.setText("");
        for (int i = 0; i < this.op2DimensionFilasM1; i++) {
            float[] arregloValoresFila = this.op2Vector1[i];
            this.op2PreviewM1.append(Arrays.toString(arregloValoresFila) + "\n");
        }
    }

    private void refrescarPreviwOP2M2() {
        this.op2PreviewM2.setText("");
        for (int i = 0; i < this.op2DimensionFilasM2; i++) {
            float[] arregloValoresFila = this.op2Vector2[i];
            this.op2PreviewM2.append(Arrays.toString(arregloValoresFila) + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuOperacion1;
    private javax.swing.JMenu mnuOperacion2;
    private javax.swing.JMenu mnuOperacion3;
    private javax.swing.JMenu mnuOperacion4;
    private javax.swing.JTextField op1DimensionVectores;
    private javax.swing.JButton op1GuardarVector1;
    private javax.swing.JButton op1GuardarVector2;
    private javax.swing.JButton op1SumarVectores;
    private javax.swing.JTextField op1ValorVector1;
    private javax.swing.JTextField op1ValorVector2;
    private javax.swing.JButton op2GuardarValorMatriz1;
    private javax.swing.JButton op2GuardarValorMatriz2;
    private javax.swing.JTextField op2M1columnas;
    private javax.swing.JTextField op2M1filas;
    private javax.swing.JTextField op2M2columnas;
    private javax.swing.JTextField op2M2filas;
    private javax.swing.JButton op2MultiplicarMatrices;
    private javax.swing.JTextArea op2PreviewM1;
    private javax.swing.JTextArea op2PreviewM2;
    private javax.swing.JTextArea op2ResultadoMultiplicacion;
    private javax.swing.JComboBox<String> op2SelectorFilaMatriz1;
    private javax.swing.JComboBox<String> op2SelectorFilaMatriz2;
    private javax.swing.JTextField op2ValorColumaMatriz1;
    private javax.swing.JTextField op2ValorColumaMatriz2;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelOperacion1;
    private javax.swing.JPanel panelOperacion2;
    private javax.swing.JPanel panelOperacion3;
    private javax.swing.JPanel panelOperacion4;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
